version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: autores_obras_db
    environment:
      MYSQL_ROOT_PASSWORD: "joselito157"
      MYSQL_DATABASE: "stefanini"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pjoselito157"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-autores-obras:latest
    container_name: api_autores_obras
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/stefanini"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "joselito157"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data: {}


